version: "3"
services:
  xxl-job-db:
    build:
      context: doc/db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: "root_pwd"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
  xxl-job-admin:
    build:
      context: .
      dockerfile: Dockerfile
    image: xxl-job
    depends_on:
      - xxl-job-db
    ports:
      - "8080:8080"
    command: java -jar xxl-job-admin.jar
  xxl-job-executor:
    image: xxl-job
    depends_on:
      - xxl-job-admin
    command: java -jar xxl-job-executor.jar
